### ISSUE TITLE
No prefix argument in diff-hl-diff-goto-hunk

### ISSUE THREAD

**Issue by link0ff** [dgutov/diff-hl#149]
The command `vc-diff` (bound to `C-x v =`) supports a prefix arg that allows to read two revisions to compare. In diff-hl-mode, `vc-diff` is remapped to `diff-hl-diff-goto-hunk`.  But the problem is that `diff-hl-diff-goto-hunk` doesn't support the same prefix arg, so it disables the feature of comparing two revisions.  Please add the same prefix arg `historic` to `diff-hl-diff-goto-hunk`.

**Comment by link0ff** [comment]
No need to hurry implementing this because it's likely that a new function `diff-goto-line` that could be added in https://debbugs.gnu.org/36526 will obsolete this request.

**Comment by dgutov** [comment]
OK, but isn't `diff-hl-diff-skip-to` a much shorter implementation of the same feature?

Or do his patches add some other features?

**Comment by link0ff** [comment]
His patches add other improvements:
1. support context diffs;
2. support multiple files in the same patch (e.g. by `C-x v D`)

**Comment by dgutov** [comment]
Thanks. Let's see how it develops.

**Comment by dgutov** [comment]
Not much has happened in that discussion since then, so in the meantime, I've added support for the prefix argument here.

One thing I wasn't sure about is when to apply `diff-hl-diff-skip-to`, and when not do it anymore. So for now it only happens when the second revision is empty (meaning to use the work tree). Any better suggestions welcome.
