### ISSUE TITLE
Feature Request: Support diff-buffer-with-file

### ISSUE THREAD

**Issue by bastianbeischer** [dgutov/diff-hl#176]
It would be amazing if this mode would support showing fringe indicators for unsaved files, by comparing the buffer with the on-disk file (through diff-buffer-with-file).

I realize this has nothing to do with vc, so I don't know how easy this is to implement. But I would find it rather useful, as I find that "what did I actually change in this file" is a very relevant question before saving, that could need some helpful advice. Running a full diff-buffer-with-file is a bit cumbersome...

**Comment by dgutov** [comment]
That's `diff-hl-flydiff-mode`, isn't it?

**Comment by bastianbeischer** [comment]
Aha! Yes, basically. However, that only works if the underlying file is in vc right?

**Comment by dgutov** [comment]
Uh, yes. It compares to the last committed (or staged) version.

I suppose for non-version-controlled files the issue of whether to save or not, might actually be more important. It should be possible to implement this without too much trouble. Maybe even in this package (as a separate minor mode).

I wonder if using the same look might be problematic, since it could give an impression that the buffer is version-controlled.

**Comment by dgutov** [comment]
Closing as not planned, but if someone wanted to submit a PR with an implementation, I would definitely give it a look.
