### ISSUE TITLE
Feature request: stage region

### ISSUE THREAD

**Issue by NicholasBHubbard** [dgutov/diff-hl#195]
Very often I have two or more changes that I would like to stage then commit separately, but are part of the same hunk. Unfortunately diff-hl does not support staging sections of hunks. It would be very nice if there was a function `diff-hl-stage-region`, that would stage just the highlighted portion of a hunk. 

Currently for this situation I use Magit's `magit-stage` function which automatically detects if the region is active, and if so only stages the highlighted region. This is very awkward however as I do all my other staging through diff-hl.

**Comment by dgutov** [comment]
Sure, why not.

What does `magit-stage` do when the beginning or the end of a region falls inside one of the hunks? Does it stage it whole? If so, it should be very easy to copy that behavior here.

**Comment by NicholasBHubbard** [comment]
The `magit-stage` region staging behavior only works from the `magit-status` buffer. From a regular buffer, regardless of if the region is active or not, `magit-stage` stages every change in the file (with a call to `magit-stage-file`). However from the `magit-status` buffer you can highlight a portion of a hunk (from the `Unstaged changes` section), and get the region staging behavior.

For this reason I do not believe that this feature could be implemented with a simple wrapper over `magit-stage`.

**Comment by dgutov** [comment]
If magit staging works not inside a buffer (or a diff buffer), then the question is moot.

It looks like I misread the original explanation. Previously, I have read the request as being able to stage multiple hunks at once (all falling into the selected region). You do want to stage partial hunks. 

Let's try to imagine how the interface would look.

Do we only do that for "green" hunks only? Because I'm not sure how to split a "blue" hunk (you would include all the deletions but only some of the additions? that's probably not what one would expect from a partial staging). And a "red" hunk spans zero lines, so you wouldn't be able to delineate any parts of it with a region.

Second question: what to do when a region begins or ends in the middle of a line?

**Comment by NicholasBHubbard** [comment]
It seems that we are on the same page now.

> what to do when a region begins or ends in the middle of a line?

`magit-stage` stages the entire line that is partially included in the region. This seems reasonable to me.

> Do we only do that for "green" hunks only?

Hmm, "red" hunks spanning zero lines is a significant problem. Ideally we would be able to stage only some of the deleted lines in a "red" hunk, but I don't see how that would be possible with `diff-hl`'s current interface. However I personally would be fine with "red" hunks not being supported for this feature.

"Blue" hunks on the other hand must be supported in a sensible way, otherwise I don't see a point in adding this feature at all. The way this feature should behave for "blue" hunks is that only the additions/changes/deletions that are on lines in the region should be staged.

**Comment by dgutov** [comment]
> Hmm, "red" hunks spanning zero lines is a significant problem. Ideally we would be able to stage only some of the deleted lines in a "red" hunk, but I don't see how that would be possible with diff-hl's current interface.

Right.

> However I personally would be fine with "red" hunks not being supported for this feature.

Okay.

> "Blue" hunks on the other hand must be supported in a sensible way, otherwise I don't see a point in adding this feature at all. The way this feature should behave for "blue" hunks is that only the additions/changes/deletions that are on lines in the region should be staged.

How would one determine which of the deletions belong to the region, though? Just counting the lines? That's just as likely to give inaccurate results.

> Thinking it over a bit more, only supporting "green" hunks would still be useful even if "blue" hunks are not supported, though it may confuse users that expect it work with "blue" hunks as well.

Could be a little confusing, yes.

On a related note, the latest version of VC (in Emacs 29) contains a new feature heavily inspired by [commit-patch](https://github.com/caldwell/commit-patch/) where you edit the current vc diff (a result of e.g. `C-x v D`), then press `C-x v v`, enter the message and commit the result. There is no separate staging step with this usage, though (that just happens behind the scenes).

**Comment by NicholasBHubbard** [comment]
Okay then, I understand the problem with "blue" hunks. 

Personally, I would still vote for implementing this feature to only work with "green" hunks as this is still quite a useful feature. However, I understand if you believe that the lack of support "blue" and "red" hunks will be confusing for users and make for a feature that feels incomplete.

**Comment by dgutov** [comment]
Does Magit have a solution for its counterpart of "blue" hunks, BTW?

Because the alternative here would be to pop up a diff-mode buffer with its editing commands (e.g. splitting and deleting), but that's more keypresses for sure.

**Comment by NicholasBHubbard** [comment]
Yes, `magit-stage` works with both "blue" and "red" hunks which works because you are interacting directly with a diff. For this reason, your idea to pop-up a diff-mode buffer should work for all the types of hunks.

The `magit-stage` workflow is quite clunky as you have to open the `magit-status` buffer, find the file that you are working on in the `unstaged changes` section, search through that files diff for the change you want to stage, then highlight the portion of the change you want to stage.

If diff-hl popped up a diff-mode buffer positioned at the current hunk, that would eliminate all but the final step of highlighting the portion of the change you want to make. This would be a significant improvement.

**Comment by dgutov** [comment]
Speaking of popping a buffer, how do you like the new feature in Emacs 29?

One where you can take an existing diff (e.g. from `C-x v D`), edit it (by killing a few hunks, for example -- the binding is `k`), and then commit the result using `C-x v v`.

That doesn't preclude adding a new feature to `diff-hl`, and Magit users would likely prefer to stay with the staging workflow, but I'd like to have more people aware of existing VC functionality.

**Comment by dgutov** [comment]
Here's a change you can try: https://github.com/dgutov/diff-hl/commit/b68fc2f8e68132187d1799d0295aecadddd350bf

The branch is called `feature/diff-hl-stage-some`.

It doesn't react to the current region, but allows you to edit the diff before staging. Let me know how that works, and whether the preliminary selection through the region would still be useful.

**Comment by NicholasBHubbard** [comment]
Thanks for working on this! I spent a good amount of time playing with `diff-hl-stage-some` but I am not understanding how to use it.

I have a file with these three added lines (1 green hunk)

![added-lines](https://github.com/dgutov/diff-hl/assets/67754854/339fe5ea-071f-4286-b2e3-a72506bf53e9)
I would like to stage only the first line ("hello"). 

From the `*diff-hl-stage-some*` I am able to split the hunk with `diff-split-hunk`

![split-hunk](https://github.com/dgutov/diff-hl/assets/67754854/74d160df-a6e5-46d1-bd22-7b0e3f8fbb91)

From here though, I do not know how I can stage just the first hunk. When I put my cursor on the first hunk and run `M-x diff-hl-stage-current-hunk` I get `Only git supports staging; this file is controlled by nil`. 

If I run `M-x diff-hl-stage-finish` then I get the error `Failed (status 1): git --no-pager apply --cached ../../../../tmp/diff-hl-stage-patchrZajI7`.

How can I stage just the first hunk from the `*diff-hl-stage-some*` buffer?

By the way, I am using Emacs 27.2.

**Comment by dgutov** [comment]
> From here though, I do not know how I can stage just the first hunk. When I put my cursor on the first hunk and run M-x diff-hl-stage-current-hunk I get Only git supports staging; this file is controlled by nil

Like the initial message says (one displayed when the diff buffer is shown), you need to edit the diff and then press <kbd>C-c C-c</kbd>.

So, you've split the hunk, next you need to kill the other one (with <kbd>k</kbd>) and press <kbd>C-c C-c</kbd> - that should stage the hunk and kill the diff buffer.

Sometimes that still doesn't work (in my testing) because Git doesn't accept the resulting diff - if you encounter that, we'll investigate further. But in seemed to work in most of the cases I've tried.

**Comment by NicholasBHubbard** [comment]
Ohhh, I see now.

This is inconvenient if the file has many hunks as you need to kill all the hunks besides the one you actually want to stage. As a new user of this, I was expecting there to be a function for staging the hunk at point. I understand that this is a vc deficiency and not a diff-hl one though.

I do however like the approach of selectively staging from the diff buffer.

**Comment by dgutov** [comment]
Your idea with staging individual hunks from the diff buffer also sounds workable, we could fall back to it if the proposed implementation turns out to have more problems. But it has its own usability issues - like how to ensure that the diff is fresh enough, what to do when the user tries to stage the same hunk (or parts of it) several times, and so on.

It's difficult to create a consistent UI without showing the list of already staged changes, etc, basically, without reimplementing the corresponding Magit buffer.

**Comment by dgutov** [comment]
> This is inconvenient if the file has many hunks as you need to kill all the hunks besides the one you actually want to stage. As a new user of this, I was expecting there to be a function for staging the hunk at point. I understand that this is a vc deficiency and not a diff-hl one though.

Everything could be added, including new VC commands and so on. Question is, what would be both ergonomic and require less code to implement.

Regarding "you need to kill all the hunks besides the one", I could either add new commands ("kill all the hunks after current", "...before current"), or "keep only the hunks in the region". Or look at the region bounds when `diff-hl-stage-some` is called and only include the hunks that are inside/touching the region.

**Comment by NicholasBHubbard** [comment]
I like the idea of "kill all the hunks after/before" the current hunk. You could then use these to implement both "keep only the hunk at point" and "keep only the hunks in region".

**Comment by ouboub** [comment]
>>> "NH" == Nicholas Hubbard ***@***.***> writes:

   > Ohhh, I see now.
   > This is inconvenient if the file has many hunks as you need to kill
   > all the hunks besides the one you actually want to stage. As a new
   > user of this, I was expecting there to be a function for staging the
   > hunk at point. I understand that this is a vc deficiency and not a
   > diff-hl one though.

   > I do however like the approach of selectively staging from the diff buffer.

Sorry for jumping into this discussion. I am also using 
diff-hl-diff-goto-hunk or sometimes simply vc-diff.

And I do then commit (and I don't see why this should be different to
staging, but maybe I am missing a central point) sometimes only some of
the hunks.

In the case that there are 10 hunks and I only want to commit one.
I run toggle-read-only, delete the stuff I don't need, and
toggle-read-only again, and then commit. That works.



-- 
I strongly condemn Hamas heinous despicable pogroms/atrocities on Israel
I strongly condemn Putin's war of aggression against Ukraine.
I support to deliver weapons to Ukraine's military. 
I support the EU and NATO membership of Ukraine. 


-- 
I strongly condemn Hamas heinous despicable pogroms/atrocities on Israel
I strongly condemn Putin's war of aggression against Ukraine.
I support to deliver weapons to Ukraine's military. 
I support the EU and NATO membership of Ukraine.

**Comment by dgutov** [comment]
@NicholasBHubbard

> I like the idea of "kill all the hunks after/before" the current hunk. You could then use these to implement both "keep only the hunk at point" and "keep only the hunks in region".

The latter could be easier to use though, because the additional commands would require new bindings (which one also has to discover and then remember), whereas just using the region bounds active was`diff-hl-stage-some` invoked you don't have to learn any additional commands.

Neither option is particularly difficult implementation-wise, so it's really a question of what would function better.

**Comment by dgutov** [comment]
@ouboub 

> And I do then commit (and I don't see why this should be different to
staging, but maybe I am missing a central point) sometimes only some of
the hunks.

I believe you are referring to the feature that's new to Emacs 29.1, and which I've mentioned up-thread (doing a commit from a vc-diff buffer). It's my first choice as well, but I imagine others might want to stay with their existing staging-based workflows, for example if they're using Magit.

Staging is perhaps only different in that a person using a staging workflow might be more inclined to commit a partial set of changes, regularly. So being able to speed that process up could be more valuable.

> In the case that there are 10 hunks and I only want to commit one.
I run toggle-read-only, delete the stuff I don't need, and
toggle-read-only again, and then commit. That works.

BTW, you often don't need to toggle read-only off to do that: the <kbd>k</kbd> binding works in read-only mode too (because it's actually a "structural editing" mode, not the "don't change anything" mode). And undo also works (<kbd>M-_</kbd>).

But with read-only-mode off it's easier to just select a region until eob and delete it all, I suppose.

**Comment by NicholasBHubbard** [comment]
I personally would only use "keep only the hunk at point" and "keep only the hunks in region".

**Comment by dgutov** [comment]
I've pushed the region feature (select the hunks with the region first and then invoke `C-x v S`). See how you like it.

**Comment by NicholasBHubbard** [comment]
This works well!

**Comment by dgutov** [comment]
Excellent. Merged!
